### ISSUE TITLE
Group agreements

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#955]
- [ ] agreements table - same language uses same agreement row across groups. Columns: id, text
- [ ] groups_agreements - columns: id, group_id, agreement_id
- [ ] users_agreements - group_id, agreement_id, agreed_to
