### ISSUE TITLE
Group roles & responsibilities

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#956]
https://www.figma.com/file/jaHPBbpLu2Pbiywr3Y1inx/Roles-%26-Responsibilities?type=design&node-id=1-2&mode=design&t=DTA7UBeNKer3zW9B-0

- [ ] system_responsibilities table.
- - [ ] name
- - [ ] description (copy here: https://docs.google.com/document/d/1EUiiTtIyGAIEZRwF1uJtDk-FAyj3HchRZ5Kwf62cSv8/edit#heading=h.j8sxm8kc5x8)
- [ ] System responsibilities to start with:
- - [ ] Administration: Allows for editing group settings, exporting data, and deleting the group.
- - [ ] Add Members: The ability to invite and add new people to the group, and to accept or reject join requests.
- - [ ] Remove Members: The ability to remove a member from the group.
- - [ ] Remove Content: When content appears in your community that violates your agreements, you have the ability to remove that post from the group.
- - [ ] Assign roles & responsibilities to others (only ones you have). I think we hold off on this one for now as it feels tricky
- [ ] groups_responsibilities table
- - [ ] group_id
- - [ ] name
- - [ ] description
- [ ] system_roles table
- - [ ] name
- - [ ] description
- - [ ] icon
- [ ] Built in Roles:
- - [ ] Manager: The manager is empowered to do everything related to group administration.
- - [ ] Moderator: Moderators are expected to actively engage in discussion, encourage participation, and take corrective action if a member violates group agreements.
- - [ ] Host: Hosts are responsible for cultivating a good atmosphere by welcoming and orienting new members, embodying the group culture and agreements, and helping members connect with relevant content and people.
- [ ] roles_responsibilities table
- - [ ] responsibility_id (or have separate system_responsibility_id and groups_responsibilities_id columns and choose when one to use based on the responsibility_type column?)
- - [ ] responsibility_type: either 'system' or 'group'
- members_roles table changes
- - [ ] role_type: 'system' or 'group' 
- - [ ] system_role_id for use when role type is system (or does group_role_id become role_id and point to either the system_roles table or the group_roles table? should go the same direction that the roles_responsibilities table goes in this regard)
- [ ] Add an everyone role that can be used to give a responsibility to everyone? This is a bonus or future thing

**Comment by thomasgwatson** [comment]
What does system_roles do here?

system_responsibiltiies:
A table covering the different powers/responsibilities that a user can have on the platform. Each one maps to something that can change the state of the platform in some way

group_responsiblities:
A table covering powers/responsibilities that a user can have outside of the platform, in the context of a specific group. Useful for group members to understand their group context

system_roles:
? Is this for platform-wide roles? Like for us, as an example? That show up, regardless of group context?

roles_responsiblities:
Allows us to map many-to-many relationships between roles to responsiblities

members_roles:
Allows us to map many-to-many relationships between members and roles

Do you recall why we decided to split the responsibilities into two tables, rather than just have one table that has two types? Yes, they are slightly different but splitting them across tables complicates roles_responsiblities. I know we have done similar splits elsewhere, but those splits tend to need further handling at the ORM and query level.

**Comment by thomasgwatson** [comment]
Reminder to myself: group_roles already exists, as does members_roles

Ok, so system_roles is the home of the built-in roles listed above. Maybe even better to have that table names built_in_roles, common_roles, or predefined_roles instead? I can see us needing a platform_roles or system_roles table that doesn't map to member_roles and covers platform-wide responsibilities.

For 'system_roles' and 'group_roles' relating to members_roles:
What about: members_roles has role_id and it always joins to both into queries hitting the members_roles; this would require one of the two tables to not have "auto incrementing ids" and instead use UUIDs. This seems simple from a SQL perspective but gets more hazy when I think about the impact on the ORM models etc... I do vaguely recall that you can effectively overwrite the default queries in the ORM on the respective model, does that sound right?

And yes, for the responsibilities: I guess I'm still not convinced there is a compelling reason to split them into two tables. Its 'group_responsibilities', not the many-to-many relationship tracking '**groups**_responsibilities' and the relationship to the specific memberships would be tracked roles_responsiblities. So I feel like we could just have one table covering both types, and skip on having to add unusual queries etc into the other models

**Comment by tibetsprague** [comment]
sure, like common_roles

**Comment by tibetsprague** [comment]
I dont understand your proposal for responsibilities. are you saying we should copy the common responsibilities into group_responsibilities for every group? what if we ant to change the name of description of one of them? then you'd have to change it foe every single group

**Comment by tibetsprague** [comment]
that makes sense to me. I do think for now any custom responsibilities made in a group will only be for that group, but like you said could see sharing them in the future

**Comment by thomasgwatson** [comment]
Ok, stepping through common_roles (previous system_roles):
They will need a direct relationship to their responsibilities; many-to-many, so _common_roles_responsibilities_
They will also need a direct relationship to a membership; _common_roles_group_memberships_

In this way, the common_roles are more or less separated from the group_roles. They would both be requested via a GroupMembership. They would require distinct 'setters' for creating new relationships (when a group assigns someone one of the common_roles), so there is duplication there. But I think its more straightforward to have a little duplication of simple code, than trying to have one relationship table (like members_roles) have to target rows in different tables. So in effect, this is akin to the 'two queries getting merged into one array' option you mentioned earlier but instead of that merging happening in the backend, it can optionally happen anytime a GroupMembership is requested.

Does that make sense?
