### ISSUE TITLE
Improve email digests

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#962]
- [x] [Don't show posts and comments from current user (?)](https://github.com/Hylozoic/hylo-node/issues/946)
- [x] [Don't include past events](https://github.com/Hylozoic/hylo-node/issues/960)
- [ ] [Don't send duplicate content when a post appears in multiple groups](https://github.com/Hylozoic/hylo-node/issues/961)
- [ ] Improve formatting, especially of bullet lists and headers: https://github.com/Hylozoic/hylo-node/issues/944
- [ ] Show more info/context about new comments
- [ ] Show more info/context about new chats?
- [ ] Don't link internally within the email for short digests
