### ISSUE TITLE
Proposal post type

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#969]
https://docs.google.com/document/d/1EUiiTtIyGAIEZRwF1uJtDk-FAyj3HchRZ5Kwf62cSv8/edit#heading=h.j8sxm8kc5x8

- [ ] New post type 'proposal'
- - [ ] New fields: Quorum = minimum # votes needed for vote to pass
- - [ ] Status: options = Discussion phase , voting phase, completed, quorum not reached (or is this an outcome?). The status changes from discussion to voting when start_time starts, or can be done manually. It changes from voting to completed when end_time reached if that is set, or can be changed manually.
- - [ ] Outcome: Pass, Fail, Quorum not Reached (or is this a Status?)
- - [ ] Anonymous? boolean (this is for v2, unless its super easy to squeeze in)
- [ ] proposal_options table
- - [ ] proposal_id
- - [ ] text: string (required. meant to be a short option like "yes", "consent"...)
- - [ ] description: text (optional. to describe what voting this option really means)
- [ ] proposal_votes table
- - [ ] proposal_id
- - [ ] option_id
- - [ ] user_id
- - [ ] created_at
- - [ ] updated_at (can people change their votes?? i think so)
- bonus: a new responsibility which allows you to create proposals called Governance (and a new common role for it? or maybe it just one people can use for their own roles.) By default everyone can do this?

**Comment by thomasgwatson** [comment]
Is the current intention to just load up the post table with all these extra fields?

**Comment by tibetsprague** [comment]
Yeah, I think thats best and easiest for now

**Comment by thomasgwatson** [comment]
Pros and cons of just adding a proposal JSONB column and stuffing it all in there? 

I think that would allow for better future extensibility of proposals. The JSONB format makes it a little more annoying to query or index but I am struggling to imagine use-cases where we would need to query/filter/index the internal data on a proposal column... Can you think of any?

**Comment by tibetsprague** [comment]
We definitely will want to query by status to show proposals in different statuses, and probably by outcome too? Hmm. Jsonb honestly feels like more trouble than it’s worth to me. You still need migrations to deal with it often and they end up being more tricky than if they were just columns. On Feb 15, 2024, at 6:18 PM, Tom Watson ***@***.***> wrote:﻿
Pros and cons of just adding a proposal JSONB column and stuffing it all in there?
I think that would allow for better future extensibility of proposals. The JSONB format makes it a little more annoying to query or index but I am struggling to imagine use-cases where we would need to query/filter/index the internal data on a proposal column... Can you think of any?

**Comment by thomasgwatson** [comment]
Ok, that brings up another prickly point: 'status'

If we want to have it be automatically determined by start/end time AND also manually set-able (as per Clare's comments on the doc), there is lots of bug-surface area there.

- Do we rely on a chron-job to look at the times and flip values in the status column?
- Do we have a check on the front-end/mobile, where if someone loads a proposal and the status doesn't sync up with the times, EVO/mobile sends a cheeky update query to prompt the backend to update the db 😆 

On the front-end, we could just ignore the status value if there is a start/end time but that would cause many pains in the butt from a query perspective.

Any thoughts on what approach we should aim at?

**Comment by thomasgwatson** [comment]
maybe pg_cron is actually the answer here: cron job attached to the db itself

**Comment by thomasgwatson** [comment]
template/default options:

Consent: Consent, Objection
Consensus: Agree, Abstain, Disagree, Block
etc, etc

Do we want to put those into the database or just hardcode them into the hylo-shared?

**Comment by tibetsprague** [comment]
I think just put them on the front-end in hylo-evo. What's the advantage of putting them in hylo-shared?

**Comment by tibetsprague** [comment]
we already run a cron on the back-end every 10 minutes, so lets just use that to check/update status. cron.js. I think if the start_time begins and its still in discussion phase we switch to voting, but that can be overwritten at which point we don't switch back. We could track in a field that it has been manually set and don't update again, but maybe easier to just check during cron if we are within 10 minutes of the start_time and just do that switch one time. That make sense?

**Comment by thomasgwatson** [comment]
I suggested hylo-shared to avoid duplicating it react native... but we are pretty behind on that overall project 😂

And yes, I think that makes sense for the cron job. We aren't going to track whether an automated status update has occurred. At some stage, a heavy-weight version of governance stuff should track *any* update or change to a proposal, for auditing and transparency purposes. Not for now of course.

IF we stick to the 10 minute cronjob:

Smol user-angst possibility:
- DB updated status to COMPLETED, 1-10 minutes before the end time and it seems like its closed when it shouldn't be
- Initially I thought "Well, we can just prioritize the end-time on the front-end, and still show it as voting"
- But then it will also not show up in some queries for a few minutes before closing...

Proposals are mostly going to be pretty benign but I'm leery of setting this sort of thing up as loosy-goosy as "accurate to ten minutes" in case a community gets serious about their use and a premature closing causes angst.

I propose we go with a every minute cron-job, what do you think?

**Comment by thomasgwatson** [comment]
Do you really want it to be proposal_id and not just post_id? I think we should just stick with post_id

**Comment by tibetsprague** [comment]
ah yeah post_id is good

**Comment by tibetsprague** [comment]
every minute cron jobs works for me

**Comment by tibetsprague** [comment]
oh yeah Hylo-shared makes sense for use in React Native too 👍

**Comment by thomasgwatson** [comment]
@tibetsprague I posted up a migration but as a thought experiment:
What if we just stored a user's vote on a proposal in posts_users? We have to make a user a follower of the post when they vote anyway... One weakness would be if we wanted to expand in the vote to allow one user voting for several options (Like timeslots or approval voting style), this path wouldn't work as well.

Partially this is just an exercise in me better understanding posts_users and how users end up following posts... Reading through the model code now

**Comment by thomasgwatson** [comment]
I guess I can just call `Post.addFollowers`

**Comment by tibetsprague** [comment]
hmm, good thought, but yeah I do think we should pave the way for voting on multiple options. in fact we should actually decide if we want to enable that right now for polls. probably we do.

**Comment by thomasgwatson** [comment]
Proposals discussion points for product:

**loading pattern for options/votes**
Where we want to show proposal information impacts their loading pattern.
- Always loading everything whereever posts are loaded (my assumed default)
- Only full load on PostDetail view (probably need some sort of summary of votes for stream views)

**Design clutter from reactions/emojis**
Do we force each proposal option to have an emoji and basically sub votes in for emojis on Proposals?
- allows us to save space on stream views of Proposals
- Easy re-use of existing
- Does having votes and reactions on a post cause confusion? Does substituting one (votes) into the place of the other (reactions) cause confusion? (Note: this substitution is NOT in lieu of a full vote graphic at the bottom of the proposal-post)
- Risk of analysis-paralysis for users: how to pick the right emoji for the option? Somewhat mitigated by having the default setups. We could also make emojis optional (all or none have emojis) and just use number emojis as defaults on the front-ends (eg: 1️⃣)

@brodeur @cpolitano for discussion tomorrow

**Comment by tibetsprague** [comment]
Are we supporting multi-votes or not in this MVP?

**Comment by thomasgwatson** [comment]
Product follow-up
- Keep reactions as is
- Find where we can add vote displays to stream (card and item views?)
- Load enough data to show summary

**Comment by thomasgwatson** [comment]
@tibetsprague thinking about multi-votes and removing the 'UpdatedAt' column of proposal_votes:
- If we allow multi-voting, it somewhat invalidated the idea that a row in the proposal_votes table ever gets updated
- You could have three different vote rows for one proposal. The original vote is still there, it isn't updated when the others are added
- Adding and removing those votes will be creation and destruction acts
- If we have those mutations for multi-votes, I don't see why we'd use a different pattern (update) just because its the single-vote use-case

Even if we aren't setting up for multi-votes straight away, I'm inclined to build mutations that will work for both

Unless I am missing something here, I'll just remove UpdatedAt and build mutations that could be used for single or multi-vote updating

**Comment by tibetsprague** [comment]
Hmm. It is a different use case though to change your vote than to vote on multiple things. But in that case yes we could just remove the old vote and add a new one. Or only pull the latest vote for that proposal. So I think that makes sense.

**Comment by tibetsprague** [comment]
and I agree that prepping for multi-votes is a good idea
